name: docker-image-workflow
on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses:  actions/checkout@v3  
      with: 
        repository: Newerasolutionsa/my-simple-python-application

   
        


